package tn.com.st2i.project.administration.model;

import javax.persistence.Column;
import javax.persistence.Entity;
/**
 * Generated by Nafkan Hibernate Tools 4.3.1
 * 
 * Postgres dataBase
 *
 */
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import lombok.Data;

@Data
@Entity
@Table(name = "adm_libelle")
public class AdmLibelle implements java.io.Serializable, Cloneable {
	private transient static final long serialVersionUID = 1L;

	@SequenceGenerator(allocationSize = 1, initialValue = 1, sequenceName = "adm_libelle_id_seq", name = "adm_libelle_id_seq")
	@GeneratedValue(generator = "adm_libelle_id_seq", strategy = GenerationType.SEQUENCE)
	@Id
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@Column(name = "code", length = 50)
	private String code;

	@Column(name = "val_fr", length = 512)
	private String valFr;

	@Column(name = "val_ar", length = 512)
	private String valAr;

	@Column(name = "ordre")
	private Integer ordre;

	public AdmLibelle clone() throws CloneNotSupportedException {
		return (AdmLibelle) super.clone();
	}
}
